openapi: 3.0.3
info:
  title: Synaxis Distributed Synchronization System
  description: API for distributed lock management, queue, and cache coherence
  version: 0.1.0
  contact:
    name: Synaxis Team

servers:
  - url: http://localhost:8000
    description: Lock Manager
  - url: http://localhost:8100
    description: Queue Node
  - url: http://localhost:8200
    description: Cache Node

paths:
  /health:
    get:
      summary: Health check
      operationId: healthCheck
      responses:
        "200":
          description: Node is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"

  /message:
    post:
      summary: Send message to node
      operationId: sendMessage
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
              description: ormsgpack serialized Message
      responses:
        "200":
          description: Message processed successfully
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "204":
          description: Message processed, no response
        "500":
          description: Internal error

components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: healthy
        node_id:
          type: string
          example: node-1

    Message:
      type: object
      required:
        - msg_type
        - sender_id
        - payload
      properties:
        msg_type:
          type: integer
          description: MessageType enum value
        sender_id:
          type: string
        payload:
          type: object
        term:
          type: integer
          default: 0
        message_id:
          type: string
          format: uuid
        timestamp:
          type: number
          format: double

    LockAcquirePayload:
      type: object
      required:
        - resource_id
        - lock_type
      properties:
        resource_id:
          type: string
        lock_type:
          type: string
          enum: [SHARED, EXCLUSIVE]
        timeout:
          type: number
          default: 30.0

    LockReleasePayload:
      type: object
      required:
        - resource_id
        - lock_id
        - lock_type
      properties:
        resource_id:
          type: string
        lock_id:
          type: string
        lock_type:
          type: string
          enum: [SHARED, EXCLUSIVE]
        fencing_token:
          type: integer

    LockResponse:
      type: object
      properties:
        success:
          type: boolean
        lock_id:
          type: string
        fencing_token:
          type: integer
        expires_at:
          type: number

    QueuePublishPayload:
      type: object
      required:
        - topic
        - payload
      properties:
        topic:
          type: string
        payload:
          type: string
          format: binary
        key:
          type: string
          nullable: true

    QueueConsumePayload:
      type: object
      required:
        - topic
        - consumer_group
      properties:
        topic:
          type: string
        consumer_group:
          type: string
        max_messages:
          type: integer
          default: 10

    QueueAckPayload:
      type: object
      required:
        - message_id
      properties:
        message_id:
          type: string

    QueueMessage:
      type: object
      properties:
        message_id:
          type: string
        topic:
          type: string
        payload:
          type: string
          format: binary
        partition:
          type: integer
        offset:
          type: integer
        timestamp:
          type: number
        state:
          type: integer
        delivery_count:
          type: integer

    CacheReadPayload:
      type: object
      required:
        - key
      properties:
        key:
          type: string
        from_memory:
          type: boolean
          default: false

    CacheWritePayload:
      type: object
      required:
        - key
        - value
      properties:
        key:
          type: string
        value:
          type: string
          format: binary

    CacheInvalidatePayload:
      type: object
      required:
        - key
      properties:
        key:
          type: string

    CacheResponse:
      type: object
      properties:
        found:
          type: boolean
        value:
          type: string
          format: binary
        version:
          type: integer
        success:
          type: boolean
        has_copy:
          type: boolean
        invalidated:
          type: boolean

  messageTypes:
    description: |
      MessageType enum values:
      - 1: REQUEST_VOTE
      - 2: VOTE_RESPONSE
      - 3: APPEND_ENTRIES
      - 4: APPEND_RESPONSE
      - 5: HEARTBEAT
      - 6: HEARTBEAT_RESPONSE
      - 7: LOCK_ACQUIRE
      - 8: LOCK_RELEASE
      - 9: LOCK_RESPONSE
      - 10: QUEUE_PUBLISH
      - 11: QUEUE_CONSUME
      - 12: QUEUE_ACK
      - 13: QUEUE_RESPONSE
      - 14: CACHE_READ
      - 15: CACHE_WRITE
      - 16: CACHE_INVALIDATE
      - 17: CACHE_RESPONSE
      - 18: BUS_READ
      - 19: BUS_READ_X
      - 20: BUS_UPGRADE
      - 21: BUS_FLUSH
      - 22: PRE_PREPARE
      - 23: PREPARE
      - 24: COMMIT
      - 25: REPLY
      - 26: PING
      - 27: PONG
      - 28: ERROR
